### ISSUE TITLE
Service template should use MaximumPercent / MinimumHealthyPercent params

### ISSUE THREAD

**Issue by ddewaele** [IxorTalk/ixortalk-aws-cloudformation#90]
Params exist 

```
    ServiceDeploymentMaximumPercent:
        Type: Number
        Default: 200

    ServiceDeploymentMinimumHealthyPercent:
        Type: Number
        Default: 100
```

But are not used

```
            DeploymentConfiguration:
                MaximumPercent: 200
                MinimumHealthyPercent: 50
```
