### ISSUE TITLE
When running multiple instances on the same domain, cloudfront distribution for assets should include projectname

### ISSUE THREAD

**Issue by ddewaele** [IxorTalk/ixortalk-aws-cloudformation#94]
We could include `${ProjectName}-${Environment}` to the assets alias in cloudfront.
Same convention we use on other resources also (roles, buckets, ....)
```
    CloudFront:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub https://s3.eu-central-1.amazonaws.com/${S3TemplatesBucketName}/infrastructure/cloudfront.yaml
            Parameters:
                AssetsBucketName: !Sub ${ProjectName}-${Environment}-static-content
                CertificateARN: !Ref CloudFrontCertificateARN
                DistributionAlias: !Join
                  - "."
                  - - !If [ IsProd, !Sub "assets-${ProjectName}", !Sub "assets-${ProjectName}-${Environment}"]
                    - !Ref HostedZoneNameWithoutDot
```
